version: "3.8"
services:
  app:
    image: usanzadunje/laravel-dev
    container_name: itc-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "3000:3000"
    entrypoint: [ "bash","./docker-compose/init.sh" ]
    depends_on:
      - db

  queue:
    image: usanzadunje/laravel-dev
    container_name: itc-queue
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: php artisan queue:listen

  npm:
    image: node:14-alpine
    container_name: itc-npm
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "3001:3001"
    command: npm run dev

  db:
    image: mysql:5.7
    container_name: itc-db
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: mysql

volumes:
  mysql-data:
